name: Ubuntu build LXOpenbox

on:
  push:
    branches: [ "work" ]
  pull_request:
    branches: [ "work" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install required packages
      run: apt-get install autopoint m4 autoconf autotools-dev
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck

    - name: Upload a Build Artifact for Ubuntu Latest
      uses: actions/upload-artifact@v4.6.2
      with:
        # Artifact name
        name: dev-lxopenbox-release-ubuntu-latest
        # A file, directory or wildcard pattern that describes what to upload
#        path: 
        # The desired behavior if no files are found using the provided path.
              
