name: Ubuntu build LXOpenbox

on:
  push:
    branches: [ "work" ]
  pull_request:
    branches: [ "work" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install required packages
      run: sudo apt-get install autopoint gettext m4 autoconf autotools-dev libglib2.0-dev libpango1.0-dev libxext-dev x11proto-randr-dev libstartup-notification0-dev libimlib2-dev libxcursor-dev libxml2-dev 
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib64
    - name: make only SSE2/SSE4.1/SSE4.2 support
      run: make CFLAGS="-msse2 -msse4.1 -msse4.2" CXXFLAGS="-msse2 -msse4.1 -msse4.2"

    - name: Upload a Build Artifact for Ubuntu Latest
      uses: actions/upload-artifact@v4.6.2
      with:
        # Artifact name
        name: dev-lxopenbox-release-ubuntu-latest
        # A file, directory or wildcard pattern that describes what to upload
#        path: 
        # The desired behavior if no files are found using the provided path.
              
