name: Ubuntu build LXOpenbox

on:
  push:
    branches: [ "work" ]
  pull_request:
    branches: [ "work" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install required packages
      run: sudo apt-get install autopoint gettext docbook-to-man m4 autoconf autotools-dev libglib2.0-dev libpango1.0-dev libxext-dev x11proto-randr-dev libstartup-notification0-dev libimlib2-dev libxcursor-dev libxml2-dev 
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib64
    - name: make
      run: make
    - name: dpkg-deb build lxopenbox
      run: dpkg-deb --build . lxopenbox-sse4.2.deb

    - name: Upload a Build Artifact for Ubuntu Latest
      uses: actions/upload-artifact@v4.6.2
      with:
        name: dev-lxopenbox-sse4.2-release-ubuntu-latest
        # A file, directory or wildcard pattern that describes what to upload
        path: ./lxopenbox-sse4.2.deb
        # The desired behavior if no files are found using the provided path.
              
